language: python
python:  
  - "3.7"
  
install:
  - pip install -r requirements.txt
  
# deploy:
#   provider: elasticbeanstalk
#   access_key_id: $ACCESSKEYID
#   secret_access_key: $SECRETACCESSKEY
#   region: "us-east-1"  
#   app: "django-tutorial"
#   env: "django-env"
#   bucket_name: "elasticbeanstalk-us-east-1-076563148632"
#   on:
#     branch: master

script:
  - black --check .
  
after_script:
   - coveralls
